name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event_comment.body == 'recheck' || github.event_comment.body == 'I accept the KeSSie CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/cla.json'
          path-to-cla: 'https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md'
          # The custom message the bot posts
          custom-pr-sign-comment: "Thank you for your contribution! To ensure KeSSie remains sustainable, we require all contributors to sign our [Contributor License Agreement](https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md). Please comment **'I accept the KeSSie CLA'** to proceed."
          custom-allsigned-prcomment: "All contributors have signed the KeSSie CLA. ✅"
          # Lock the check until they sign
          allowlist: bot1,bot2
